loan/family/urls.py
from django.urls import path
from .views import( IndexView,
singup,
lottory,
FundCreateView,
FundListView,
FundUpdateView,
FundDeleteView,
MemberCreate,
MemberUpdate ,
MemberDelete,
ListMemberView,
DashbordView,
LoanCreate,
ListLoanView,
LoanUpdate,
LoanDelete,
WinnerListview,
WinnerDeleteView,
)
app_name = 'family'
urlpatterns =[
    path('',IndexView.as_view(),name='index'),
    path('singup/', singup, name='singup'),
    path('dashbord/createfund',FundCreateView.as_view() , name='fund_create'),
    path('dashbord/fundlist',FundListView.as_view() , name='fund_list'),
    path('singup/sand/<int:pk>/updateFund', FundUpdateView.as_view(), name='fund_update'),
    path('singup/sand/<int:pk>/deletememeber', FundDeleteView.as_view(), name='fund_delete'),
    path('singup/sand/createmember',MemberCreate.as_view() , name='create'),
    path('singup/sand/<int:pk>/updatememeber', MemberUpdate.as_view(), name='update'),
    path('singup/sand/<int:pk>/deletememeber', MemberDelete.as_view(), name='delete'),
    path('dashbord', DashbordView.as_view(), name='dashbord'),
    path('dashbord/membrList/',ListMemberView.as_view(),name='person_list'),
    path('dashbord/createLoan',LoanCreate.as_view() , name='vam_create'),
    path('dashbord/loanList/',ListLoanView.as_view(),name='vam_list'),
    path('dashbord/loanList/<int:pk>/updateLoan',LoanUpdate.as_view() , name='vam_update'),
    path('dashbord/loanList/<int:pk>/deleteLoan',LoanDelete.as_view() , name='vam_delete'),
    path('dashbord/<int:pk>/lottory',lottory,name='lottory'),
    path('dashbord/winnerlist',WinnerListview.as_view() , name='winner_list'),
    path('dashbord/winnerlist/<int:pk>/DeleteWinner',WinnerDeleteView.as_view() , name='winner_delete'),

]

loan/loan/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('family.urls'),name='family'),
    path('accounts/', include("django.contrib.auth.urls"))
]

urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

loan/family/models.py
from pickle import FALSE
from secrets import choice
from tabnanny import verbose
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.


class Sandogh(models.Model):
     sandogh = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name="مدیر")
     name = models.CharField(max_length=60 , blank= False ,verbose_name="نام صندوق")
     saham = models.IntegerField( blank= False , verbose_name="تعداد سهام")
     m_saham = models.IntegerField(blank=False , verbose_name= 'مبلغ هر سهم ')
     m_sandogh = models.IntegerField(blank=False , verbose_name= 'موجودی صندوق ')
     shomare_hesab =models.IntegerField(blank=False , verbose_name="شماره حساب")
     rolls = models.TextField(max_length=10000 , blank=True , verbose_name="توضیحات و قوانین")
     date_created = models.DateField(auto_now_add=True , verbose_name="تاریخ ایجاد صندوق")
     time = models.DateTimeField(auto_created= True ,auto_now_add=True,null=True ,verbose_name="زمان ایجاد صندوق")

     def __str__(self):
          return self.name

     def get_absolute_url(self):
          return reverse('family:dashbord' )     


class MemberManger(models.Manager):
     def state (self):
          return self.filter(status="وام نگرفته")
class Member(models.Model):
     status=models.CharField(max_length=10,choices=(('وام گرفته','وام گرفته'),('وام نگرفته','وام نگرفته')),default='وام نگرفته',verbose_name="وضعیت")
     membership=models.ForeignKey(Sandogh, on_delete=models.CASCADE , verbose_name="صندوق")
     author=models.ForeignKey(User, on_delete=models.CASCADE , verbose_name="مدیر")
     name= models.CharField(max_length=50, blank=False , verbose_name="نام")
     family=models.CharField(max_length=100, blank=True , verbose_name="نام خانوادگی")
     phone = models.IntegerField( blank=True  , verbose_name="شماره تلفن")
     t_saham =models.IntegerField( blank=False , verbose_name="تعداد سهام")
     created = models.DateField(auto_now_add=True, auto_created=True , verbose_name="تاریخ ایجاد")

     objects = MemberManger()

     class Meta :
          verbose_name ='اعضا'


     def get_absolute_url(self):
          return reverse('family:create')


     def __str__(self):
          return self.name 

class Loan(models.Model):
     STATUS_CHOICES = (
          ('پرداخت شده', 'پرداخت شده'),
          ('پرداخت نشده', 'پرداخت نشده'),
          ('در حال پرداخت', 'در حال پرداخت'),
          ('در انتظار پرداخت', 'در انتظار پرداخت'),
     )
     sandogh = models.ForeignKey(Sandogh,  on_delete=models.CASCADE , verbose_name="صندوق")
     author = models.ForeignKey(User, on_delete=models.CASCADE , verbose_name="مدیر")
     name = models.CharField(max_length=15 , blank=True , verbose_name="نام وام")
     m_vam = models.IntegerField(blank=False , verbose_name="مبلغ وام")
     m_ghest = models.IntegerField(blank=False , verbose_name="مبلغ قسط")
     t_gest = models.IntegerField(blank=False , verbose_name="تعداد قسط")
     choice = models.CharField(max_length=30, choices=STATUS_CHOICES, default='در انتظار پرداخت', verbose_name="وضعیت")
     created = models.DateField(auto_now_add=True, auto_created=True , verbose_name="تاریخ ایجاد")

     class Meta :
          verbose_name ='وام ها'


     def __str__(self):
          return self.name
   
     def get_absolute_url(self):
          return reverse('family:vam_list' )

class Lottory(models.Model):
    loan = models.ForeignKey(Loan, on_delete=models.CASCADE , verbose_name="نام وام" )
    name = models.CharField(max_length=50, blank=False , verbose_name="نام")
    family = models.CharField(max_length=100, blank=False , verbose_name="نام خانوادگی")
    created = models.DateField(auto_now_add=True, auto_created=True , verbose_name="تاریخ ایجاد")


    class Meta :
          verbose_name ='برنده ها'

    def __str__(self):
          return  self.name
     
    def get_absolute_url(self):
          return reverse('family:vam_list' , kwargs={'pk':self.pk})      

loan/family/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.forms import  ModelForm
from .models import Sandogh , Lottory


class SingUpForm(UserCreationForm):
    username = forms.TextInput()
    first_name = forms.TextInput()
    last_name = forms.TextInput()
    email = forms.EmailInput()
    password1 = forms.PasswordInput()
    password2 = forms.PasswordInput()
   
    class Meta:
        model = User
        fields =('username','first_name','last_name','email','password1','password2')
       

class SandoghForm(ModelForm):
    class Meta :
        model = Sandogh
        exclude = (' date_created','time')


class LottoryForm(ModelForm):
    class Meta :
        model = Lottory
        exclude = ('created','name','family')

loan/family/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin 
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect 
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views import generic
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from .forms import SingUpForm, SandoghForm , LottoryForm
from .models import  Member , Sandogh ,Loan ,Lottory
from .mixins import FieldsMixin ,AuthorAccessMixin
import random


# Create your views here.


class IndexView(TemplateView):
    template_name = 'family/index.html'

    # sessions
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['num_visits'] = self.request.session['num_visits']
        return context

    def get(self, request, *args, **kwargs):
        num_visits = request.session.get('num_visits', 0)
        request.session['num_visits'] = num_visits + 1
        return super().get(request, *args, **kwargs)


def singup(request):
    if request.method == 'POST':
        form = SingUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            pass1 = form.cleaned_data.get('password1')
            pass2 = form.cleaned_data.get('password2')
            if pass1 == pass2:
                user = authenticate(username=username, password=pass1)
                login(request, user)
            return redirect('family:fund_create')

    else:
        form = SingUpForm()
    return render(request, 'family/singup.html', {'form': form})






class FundCreateView(CreateView ,LoginRequiredMixin):
    model = Sandogh
    template_name = 'family/sform.html'
    fields = '__all__'
    login_url = '/login/'

# list funds and updateview and delete view

class FundListView(generic.ListView , LoginRequiredMixin):
    model = Sandogh 
    context_object_name = 'fund_list'
    template_name = 'family/fundlist.html'

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Sandogh.objects.all()
        else:
            return Sandogh.objects.filter(sandogh=self.request.user)

class FundUpdateView(UpdateView ,LoginRequiredMixin,AuthorAccessMixin ):
    model = Sandogh
    model_form = SandoghForm
    template_name = 'family/sform.html'
    fields = ('name' ,'saham','m_saham','m_sandogh','shomare_hesab')
    success_url = reverse_lazy('family:fund_list')


class FundDeleteView(DeleteView ,LoginRequiredMixin ,AuthorAccessMixin):
    model = Sandogh
    template_name = 'family/DeleteFund_form.html'
    success_url = reverse_lazy('family:fund_list')


# memeber create view uodate view delete view
class MemberCreate(CreateView ,LoginRequiredMixin , FieldsMixin ):
    model = Member
    template_name = 'family/member_form.html'
    fields = '__all__'
    login_url = '/login/'




class MemberUpdate(UpdateView ,LoginRequiredMixin,AuthorAccessMixin ):
    model = Member
    template_name = 'family/member_form.html'
    fields = ('family','phone','t_saham' ,'status')
    success_url = reverse_lazy('family:person_list')

class MemberDelete(DeleteView ,LoginRequiredMixin ,AuthorAccessMixin):
    model = Member
    template_name = 'family/DeleteMember_form.html'
    success_url = reverse_lazy('family:person_list')


# dashboard view  
class DashbordView(generic.ListView ,LoginRequiredMixin ):
    model = Sandogh
    context_object_name = 'fund'
    template_name = 'family/dashbord.html'

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Sandogh.objects.all()
        else:
            return Sandogh.objects.filter(sandogh_id = self.request.user)

# member list view
class ListMemberView(generic.ListView , LoginRequiredMixin):
    model = Member
    context_object_name = "member_list"
    template_name = "family/memberlist.html"

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Member.objects.all()
        else:
            return Member.objects.filter(author=self.request.user).order_by('membership')


# loan create view update view delete view
class LoanCreate(CreateView ,LoginRequiredMixin , FieldsMixin ):
    model = Loan
    template_name = 'family/loan_form.html'
    fields = '__all__'
    login_url = '/login/'

class ListLoanView(generic.ListView , LoginRequiredMixin):
    model = Loan
    context_object_name = "loan_list"
    template_name = "family/loanlist.html"

    def get_queryset(self):
        if self.request.user.is_superuser :
            return Loan.objects.all()
        else:
            return Loan.objects.filter(author=self.request.user)

class LoanUpdate(UpdateView , LoginRequiredMixin,AuthorAccessMixin ):
    model = Loan
    template_name = 'family/loan_form.html'
    fields = ("m_vam","m_ghest","t_gest","choice")
    success_url = reverse_lazy('family:vam_list')


class LoanDelete(DeleteView ,LoginRequiredMixin ,AuthorAccessMixin):
    model = Loan
    template_name = 'family/DeleteLoan_form.html'
    success_url = reverse_lazy('family:vam_list')
             
@login_required
def lottory(request ,pk ):
    
    winner_form = LottoryForm()
    if request.method == 'POST':
       winner_form = LottoryForm( request.POST)
       query = Member.objects.state()
       loan = Loan.objects.get(id = pk)
       ids = list(query.values_list('name','family'))
       winner = random.choice(ids)
       winner1 = Lottory.objects.create(name=winner[0],family=winner[1] , loan = loan  ) 
       winner_form = winner1
       winner_form.save()
       return redirect("family:winner_list")    
    context ={
        "winnerform" :winner_form
    } 
              
    return render(request ,'family/lottory.html' ,context)


class WinnerListview(generic.ListView):
    model = Lottory
    context_object_name = 'winner_list'
    template_name = 'family/winnerlist.html'

    def get_queryset(self):
        return Lottory.objects.all()

class WinnerDeleteView(DeleteView ,LoginRequiredMixin ,AuthorAccessMixin):
    model = Lottory
    template_name = 'family/DeleteWinner_form.html'
    success_url = reverse_lazy('family:vam_list')

                       

loan/family/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%}{%endblock title%}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
        integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'family/css/bootstrap-rtl.min.css'%} ">
    <link rel="stylesheet" href="{% static 'family/css/bootstrap-rtl.css'%} ">
    <link rel="stylesheet" href="{% static 'family/css/style.css'%}">
    <link rel="stylesheet" href="{% static 'family/css/style3.css'%}">

</head>

<body>

    {% if messages %}
            <div class="container text-center ">
                {% for message in messages %}
                  <p class="alert alert-success">{{ message }}</p>  
                {% endfor %}
            </div>
    {% endif %}

    {% block content%}

    {%endblock content%}

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous">
    </script>
   <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
</body>

</html>

loan/family/templates/base3.html
{%load static%}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>dashbord</title>

    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'family/css/bootstrap-rtl.min.css'%} ">
    <link rel="stylesheet" href="{% static 'family/css/bootstrap-rtl.css'%} ">
   
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="{% static 'family/css/style3.css'%}">
    <!-- Font Awesome JS -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
</head>

<body>
  {% if user.is_authenticated%}
    <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar" >
            <div class="sidebar-header">
                <h3><span><img src="{% static 'family/svg/account_balance_white_24dp.svg'%}" alt=""></span>    مدیریت صندوق </h3>
            </div>

            <ul class="list-unstyled components">
                <li><p>نام کاربری <span></span>:<span></span>{{request.user.username}}</p></li>
                <li>
                    <a href="{% url 'family:dashbord' %}"><span> <img src="{% static 'family/svg/dashboard_white_24dp.svg'%}" alt=""></span>  داشبورد</a>
                </li>
                <li class="active">
                   
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><span><img src="{% static 'family/svg/real_estate_agent_white_24dp.svg'%}" alt=""></span>  صندوق</a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            <a href="{% url 'family:dashbord' %}">اطلاعات صندوق </a>
                        </li>
                        <li>
                            <a href="{% url 'family:fund_list'%}">لیست صندوق ها </a>
                        </li>
                        <li>
                            <a href="{% url 'family:fund_create' %}">ایجاد صندوق جدید</a>
                        </li>

                    </ul>
                </li>
              
                <li>
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><span><img src="{% static 'family/svg/people_white_24dp.svg'%}" alt=""></span>    کاربران</a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            <a href="{% url 'family:create' %}">ایجاد کاربر</a>
                        </li>
                        <li>
                            <a href="{% url 'family:person_list' %}">لیست کاربران</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#vamSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><span><img src="{% static 'family/svg/attach_money_white_24dp.svg'%}" alt=""></span>  وام ها </a>
                    <ul class="collapse list-unstyled" id="vamSubmenu">
                        <li>
                            <a href="{% url 'family:vam_list' %}">لیست وام ها </a>
                        </li>
                        <li>
                            <a href="{% url 'family:vam_create' %}">ایجاد وام جدید</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="{%url 'family:winner_list' %}"><span><img src="{% static 'family/svg/emoji_events_white_24dp.svg'%}" alt=""> برندگان قرعه کشی</span></a>
                </li>
                <li>
                    <a href="{%url 'logout'%}"><span><img src="{% static 'family/svg/logout_white_24dp.svg'%}" alt=""></span><span></span>خروج</a>
                </li>
            </ul>

        </nav>

        <!-- Page Content  -->
            <div id="content">
                    <div class="container">
                        {% block content %}

                        {% endblock content %}
                    </div>
            </div>
      {% else %}
            <div class="container">
                <nav class="navbar navbar-expand-lg navbar-light bg-white">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a href="{% url 'family:login'%}" class="nav-link">ورود</a>
                        </li>
                    </ul>
                    
                </nav>
            </div>   
    
    </div>    
  {% endif%} 
    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        });
    </script>
</body>

</html>