loan/family/urls.py
from django.urls import path
from .views import( IndexView,
singup,
lottory,
FundCreateView,
FundListView,
FundUpdateView,
FundDeleteView,
MemberCreate,
MemberUpdate ,
MemberDelete,
ListMemberView,
DashbordView,
LoanCreate,
ListLoanView,
LoanUpdate,
LoanDelete,
WinnerListview,
WinnerDeleteView,
)
app_name = 'family'
urlpatterns =[
    path('',IndexView.as_view(),name='index'),
    path('singup/', singup, name='singup'),
    path('dashbord/createfund',FundCreateView.as_view() , name='fund_create'),
    path('dashbord/fundlist',FundListView.as_view() , name='fund_list'),
    path('singup/sand/<int:pk>/updateFund', FundUpdateView.as_view(), name='fund_update'),
    path('singup/sand/<int:pk>/deletememeber', FundDeleteView.as_view(), name='fund_delete'),
    path('singup/sand/createmember',MemberCreate.as_view() , name='create'),
    path('singup/sand/<int:pk>/updatememeber', MemberUpdate.as_view(), name='update'),
    path('singup/sand/<int:pk>/deletememeber', MemberDelete.as_view(), name='delete'),
    path('dashbord', DashbordView.as_view(), name='dashbord'),
    path('dashbord/membrList/',ListMemberView.as_view(),name='person_list'),
    path('dashbord/createLoan',LoanCreate.as_view() , name='vam_create'),
    path('dashbord/loanList/',ListLoanView.as_view(),name='vam_list'),
    path('dashbord/loanList/<int:pk>/updateLoan',LoanUpdate.as_view() , name='vam_update'),
    path('dashbord/loanList/<int:pk>/deleteLoan',LoanDelete.as_view() , name='vam_delete'),
    path('dashbord/<int:pk>/lottory',lottory,name='lottory'),
    path('dashbord/winnerlist',WinnerListview.as_view() , name='winner_list'),
    path('dashbord/winnerlist/<int:pk>/DeleteWinner',WinnerDeleteView.as_view() , name='winner_delete'),

]

loan/loan/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('family.urls'),name='family'),
    path('accounts/', include("django.contrib.auth.urls"))
]

urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

loan/family/models.py
from pickle import FALSE
from secrets import choice
from tabnanny import verbose
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.


class Sandogh(models.Model):
     sandogh = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name="مدیر")
     name = models.CharField(max_length=60 , blank= False ,verbose_name="نام صندوق")
     saham = models.IntegerField( blank= False , verbose_name="تعداد سهام")
     m_saham = models.IntegerField(blank=False , verbose_name= 'مبلغ هر سهم ')
     m_sandogh = models.IntegerField(blank=False , verbose_name= 'موجودی صندوق ')
     shomare_hesab =models.IntegerField(blank=False , verbose_name="شماره حساب")
     rolls = models.TextField(max_length=10000 , blank=True , verbose_name="توضیحات و قوانین")
     date_created = models.DateField(auto_now_add=True , verbose_name="تاریخ ایجاد صندوق")
     time = models.DateTimeField(auto_created= True ,auto_now_add=True,null=True ,verbose_name="زمان ایجاد صندوق")

     def __str__(self):
          return self.name

     def get_absolute_url(self):
          return reverse('family:dashbord' )     


class MemberManger(models.Manager):
     def state (self):
          return self.filter(status="وام نگرفته")
class Member(models.Model):
     status=models.CharField(max_length=10,choices=(('وام گرفته','وام گرفته'),('وام نگرفته','وام نگرفته')),default='وام نگرفته',verbose_name="وضعیت")
     membership=models.ForeignKey(Sandogh, on_delete=models.CASCADE , verbose_name="صندوق")
     author=models.ForeignKey(User, on_delete=models.CASCADE , verbose_name="مدیر")
     name= models.CharField(max_length=50, blank=False , verbose_name="نام")
     family=models.CharField(max_length=100, blank=True , verbose_name="نام خانوادگی")
     phone = models.IntegerField( blank=True  , verbose_name="شماره تلفن")
     t_saham =models.IntegerField( blank=False , verbose_name="تعداد سهام")
     created = models.DateField(auto_now_add=True, auto_created=True , verbose_name="تاریخ ایجاد")

     objects = MemberManger()

     class Meta :
          verbose_name ='اعضا'


     def get_absolute_url(self):
          return reverse('family:create')


     def __str__(self):
          return self.name 

class Loan(models.Model):
     STATUS_CHOICES = (
          ('پرداخت شده', 'پرداخت شده'),
          ('پرداخت نشده', 'پرداخت نشده'),
          ('در حال پرداخت', 'در حال پرداخت'),
          ('در انتظار پرداخت', 'در انتظار پرداخت'),
     )
     sandogh = models.ForeignKey(Sandogh,  on_delete=models.CASCADE , verbose_name="صندوق")
     author = models.ForeignKey(User, on_delete=models.CASCADE , verbose_name="مدیر")
     name = models.CharField(max_length=15 , blank=True , verbose_name="نام وام")
     m_vam = models.IntegerField(blank=False , verbose_name="مبلغ وام")
     m_ghest = models.IntegerField(blank=False , verbose_name="مبلغ قسط")
     t_gest = models.IntegerField(blank=False , verbose_name="تعداد قسط")
     choice = models.CharField(max_length=30, choices=STATUS_CHOICES, default='در انتظار پرداخت', verbose_name="وضعیت")
     created = models.DateField(auto_now_add=True, auto_created=True , verbose_name="تاریخ ایجاد")

     class Meta :
          verbose_name ='وام ها'


     def __str__(self):
          return self.name
   
     def get_absolute_url(self):
          return reverse('family:vam_list' )

class Lottory(models.Model):
    loan = models.ForeignKey(Loan, on_delete=models.CASCADE , verbose_name="نام وام" )
    name = models.CharField(max_length=50, blank=False , verbose_name="نام")
    family = models.CharField(max_length=100, blank=False , verbose_name="نام خانوادگی")
    created = models.DateField(auto_now_add=True, auto_created=True , verbose_name="تاریخ ایجاد")


    class Meta :
          verbose_name ='برنده ها'

    def __str__(self):
          return  self.name
     
    def get_absolute_url(self):
          return reverse('family:vam_list' , kwargs={'pk':self.pk})      

loan/family/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.forms import  ModelForm
from .models import Sandogh , Lottory


class SingUpForm(UserCreationForm):
    username = forms.TextInput()
    first_name = forms.TextInput()
    last_name = forms.TextInput()
    email = forms.EmailInput()
    password1 = forms.PasswordInput()
    password2 = forms.PasswordInput()
   
    class Meta:
        model = User
        fields =('username','first_name','last_name','email','password1','password2')
       

class SandoghForm(ModelForm):
    class Meta :
        model = Sandogh
        exclude = (' date_created','time')


class LottoryForm(ModelForm):
    class Meta :
        model = Lottory
        exclude = ('created','name','family')

loan/family/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin 
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect 
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views import generic
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from .forms import SingUpForm, SandoghForm , LottoryForm
from .models import  Member , Sandogh ,Loan ,Lottory
from .mixins import FieldsMixin ,AuthorAccessMixin
import random


# Create your views here.


class IndexView(TemplateView):
    template_name = 'family/index.html'

    # sessions
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['num_visits'] = self.request.session['num_visits']
        return context

    def get(self, request, *args, **kwargs):
        num_visits = request.session.get('num_visits', 0)
        request.session['num_visits'] = num_visits + 1
        return super().get(request, *args, **kwargs)


def singup(request):
    if request.method == 'POST':
        form = SingUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            pass1 = form.cleaned_data.get('password1')
            pass2 = form.cleaned_data.get('password2')
            if pass1 == pass2:
                user = authenticate(username=username, password=pass1)
                login(request, user)
            return redirect('family:fund_create')

    else:
        form = SingUpForm()
    return render(request, 'family/singup.html', {'form': form})






class FundCreateView(CreateView ,LoginRequiredMixin):
    model = Sandogh
    template_name = 'family/sform.html'
    fields = '__all__'
    login_url = '/login/'

# list funds and updateview and delete view

class FundListView(generic.ListView , LoginRequiredMixin):
    model = Sandogh 
    context_object_name = 'fund_list'
    template_name = 'family/fundlist.html'

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Sandogh.objects.all()
        else:
            return Sandogh.objects.filter(sandogh=self.request.user)

class FundUpdateView(UpdateView ,LoginRequiredMixin,AuthorAccessMixin ):
    model = Sandogh
    model_form = SandoghForm
    template_name = 'family/sform.html'
    fields = ('name' ,'saham','m_saham','m_sandogh','shomare_hesab')
    success_url = reverse_lazy('family:fund_list')


class FundDeleteView(DeleteView ,LoginRequiredMixin ,AuthorAccessMixin):
    model = Sandogh
    template_name = 'family/DeleteFund_form.html'
    success_url = reverse_lazy('family:fund_list')


# memeber create view uodate view delete view
class MemberCreate(CreateView ,LoginRequiredMixin , FieldsMixin ):
    model = Member
    template_name = 'family/member_form.html'
    fields = '__all__'
    login_url = '/login/'




class MemberUpdate(UpdateView ,LoginRequiredMixin,AuthorAccessMixin ):
    model = Member
    template_name = 'family/member_form.html'
    fields = ('family','phone','t_saham' ,'status')
    success_url = reverse_lazy('family:person_list')

class MemberDelete(DeleteView ,LoginRequiredMixin ,AuthorAccessMixin):
    model = Member
    template_name = 'family/DeleteMember_form.html'
    success_url = reverse_lazy('family:person_list')


# dashboard view  
class DashbordView(generic.ListView ,LoginRequiredMixin ):
    model = Sandogh
    context_object_name = 'fund'
    template_name = 'family/dashbord.html'

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Sandogh.objects.all()
        else:
            return Sandogh.objects.filter(sandogh_id = self.request.user)

# member list view
class ListMemberView(generic.ListView , LoginRequiredMixin):
    model = Member
    context_object_name = "member_list"
    template_name = "family/memberlist.html"

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Member.objects.all()
        else:
            return Member.objects.filter(author=self.request.user).order_by('membership')


# loan create view update view delete view
class LoanCreate(CreateView ,LoginRequiredMixin , FieldsMixin ):
    model = Loan
    template_name = 'family/loan_form.html'
    fields = '__all__'
    login_url = '/login/'

class ListLoanView(generic.ListView , LoginRequiredMixin):
    model = Loan
    context_object_name = "loan_list"
    template_name = "family/loanlist.html"

    def get_queryset(self):
        if self.request.user.is_superuser :
            return Loan.objects.all()
        else:
            return Loan.objects.filter(author=self.request.user)

class LoanUpdate(UpdateView , LoginRequiredMixin,AuthorAccessMixin ):
    model = Loan
    template_name = 'family/loan_form.html'
    fields = ("m_vam","m_ghest","t_gest","choice")
    success_url = reverse_lazy('family:vam_list')


class LoanDelete(DeleteView ,LoginRequiredMixin ,AuthorAccessMixin):
    model = Loan
    template_name = 'family/DeleteLoan_form.html'
    success_url = reverse_lazy('family:vam_list')
             
@login_required
def lottory(request ,pk ):
    
    winner_form = LottoryForm()
    if request.method == 'POST':
       winner_form = LottoryForm( request.POST)
       query = Member.objects.state()
       loan = Loan.objects.get(id = pk)
       ids = list(query.values_list('name','family'))
       winner = random.choice(ids)
       winner1 = Lottory.objects.create(name=winner[0],family=winner[1] , loan = loan  ) 
       winner_form = winner1
       winner_form.save()
       return redirect("family:winner_list")    
    context ={
        "winnerform" :winner_form
    } 
              
    return render(request ,'family/lottory.html' ,context)


class WinnerListview(generic.ListView):
    model = Lottory
    context_object_name = 'winner_list'
    template_name = 'family/winnerlist.html'

    def get_queryset(self):
        return Lottory.objects.all()

class WinnerDeleteView(DeleteView ,LoginRequiredMixin ,AuthorAccessMixin):
    model = Lottory
    template_name = 'family/DeleteWinner_form.html'
    success_url = reverse_lazy('family:vam_list')

                       

loan/family/templates/family/DeleteFund_form.html
{% extends "../base3.html" %}

{%load crispy_forms_tags %}
{% block title %} حذف صندوق{% endblock title %}

{% block content %}
 <div class="container mt-5">
      <h2 class="text-center">حذف صندوق</h2>
     <hr>
     <br>
      <p class="alert alert-danger text-center">ایا مطمئن هستید که صندوق {{ object.sandogh_id }} حذف شود؟</p>

                <form action="" method="POST">
                    {% csrf_token %}
                    <input class="form-control btn btn-danger text-white " type="submit" value="اره، حذف کن">
                </form>
        <br>
        <hr>

    </div>





{% endblock content %}

loan/family/templates/family/DeleteLoan_form.html
{% extends "../base3.html" %}

{%load crispy_forms_tags %}
{% block title %} حذف وام{% endblock title %}

{% block content %}
 <div class="container mt-5">
      <h2 class="text-center">حذف وام</h2>
     <hr>
     <br>
      <p class="alert alert-danger text-center">ایا مطمئن هستید که وام {{ object.vam_id }} حذف شود؟</p>

                <form action="" method="POST">
                    {% csrf_token %}
                    <input class="form-control btn btn-success " type="submit" value="اره، حذف کن">
                </form>
        <br>
        <hr>

    </div>





{% endblock content %}

loan/family/templates/family/DeleteMember_form.html
{% extends "../base3.html" %}

{%load crispy_forms_tags %}
{% block title %} حذف کاربران{% endblock title %}

{% block content %}
 <div class="container mt-5">
      <h2 class="text-center">حذف کاربر</h2>
     <hr>
     <br>
      <p class="alert alert-danger text-center">ایا مطمئن هستید که کاربر {{ object.name }} حذف شود؟</p>

                <form action="" method="POST">
                    {% csrf_token %}
                    <input class="form-control btn btn-success " type="submit" value="اره، حذف کن">
                </form>
        <br>
        <hr>

    </div>





{% endblock content %}

loan/family/templates/family/DeleteWinner_form.html
{% extends "../base3.html" %}

{%load crispy_forms_tags %}
{% block title %} حذف برنده{% endblock title %}

{% block content %}
 <div class="container mt-5">
      <h2 class="text-center">حذف برنده</h2>
     <hr>
     <br>
      <p class="alert alert-danger text-center">ایا مطمئن هستید که برنده وام {{ object.name }} حذف شود؟</p>

                <form action="" method="POST">
                    {% csrf_token %}
                    <input class="form-control btn btn-danger text-white " type="submit" value="اره، حذف کن">
                </form>
        <br>
        <hr>

    </div>





{% endblock content %}

loan/family/templates/family/Lottory.html
{%extends '../base3.html'%}
{%block title%} قرعه کشی {%endblock title%}
{% load crispy_forms_tags %}
    
    {%block content%}
        <div class="container">
            <div class="row">
                <div class="my-5">
                    <h3 class="text-danger"> نکته:</h3>
                    <p class="font-weight-light text-dark font">
                        <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان
                            گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و
                            برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی
                            می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و
                            متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی
                            الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید
                            داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان
                            مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود
                            طراحی اساسا مورد استفاده قرار گیرد.</p>
                    </p>

                </div>
                <div class="col col-12 col-sm-12">
                    <form action=" " method="POST">
                        {% csrf_token %}
                        <button type="submit"class="btn btn-success btn-block custom-btn" >انجام قرعه کشی</button>
                    </form>
                </div>

            </div>
        </div>
    {%endblock%}

loan/family/templates/family/dashbord.html
{% extends '../base3.html' %}
{% block title %}داشبورد{% endblock title %}

{% block content%}
    {% for fu in fund %}
        
            <div class="card">
                <h5 class="card-header">اطلاعات صندوق</h5>
                <div class="card-body">
                    <p class="border p-3"><label for="name">نام صندوق:</label> <span>  </span>{{fu.name}}</p>
                    <p class="border p-3"><label for="name">مدیر:</label> <span>  </span>{{ fu.sandogh }}</p>
                    <p class="border p-3"><label for="name">تعداد سهام:</label> <span>  </span> {{ fu.saham }}</p>
                    <p class="border p-3"><label for="name">مبلغ هر سهم:</label> <span>  </span>{{ fu.m_saham }}</p>
                    <p class="border p-3"><label for="name">مبلغ وام:</label> <span>  </span>{{ fu.m_sandogh }}</p>
                    <p class="border p-3"><label for="name">شماره حساب:</label> <span>  </span>{{ fu.shomare_hesab }}</p>
                    <p class="border p-3"><label for="name">زمان ایجاد:</label> <span>  </span>{{ fu.date_created }}</p>
                </div>
            </div>
        <br><br>
    {% endfor %}

{% endblock content %}

loan/family/templates/family/fundlist.html
{% extends '../base3.html' %}
{% block title %}صندوق ها{% endblock title %}


{% block content %}
   
        <table class="table table-bordered table_pos">
            <thead class="text-center text-white ">
                <th scope="col">#</th>
                <th scope="col">شماره صندوق</th>
                <th scope="col">نام صندوق</th>
                <th scope="col">نام مدیر صندوق</th>
                <th scope="col">تعداد سهام موجود </th>
                <th scope="col">ارزش هر سهام</th>
                <th scope="col">موجودی صندوق</th>
                <th scope="col">شماره حساب</th>
                <th scope="col">تاریخ ایجاد</th>
                {% if user.is_superuser or request.user.is_staf == true %}
                <th scope="col">ویرایش</th>
                <th scope="col">حذف</th>
                {%endif%}
            </thead>
            {% for fund in fund_list %}
                <tbody class=" text-center bg-white text-nowrap">
                    <tr >
                        <td >#</td>
                        <td>{{fund.id}}</td>
                        <td>{{fund.name}}</td>
                        <td>{{ fund.sandogh }}</td>
                        <td>{{fund.saham}}</td>
                        <td>{{fund.m_saham}}</td>
                        <td>{{fund.m_sandogh}}</td>
                        <td>{{fund.shomare_hesab}}</td>
                        <td>{{fund.date_created}}</td>
                        {% if user.is_superuser or request.user.is_staf == true %}
                        <td><a href="{% url 'family:fund_update' fund.id %}"><i class="fa-solid fa-pencil"></i></a></td>
                        <td><a href="{% url 'family:fund_delete' fund.id %}"><i class="fa-solid fa-trash-can"></i></a></td>
                        {%endif%}
                    </tr>

                </tbody>
            {% endfor %}
        </table>

       
{% endblock content %}

loan/family/templates/family/loan_form.html
{% extends '../base3.html'%}

{%load crispy_forms_tags %}

{% block title %}وام{% endblock title %}

{% if messages %}
    {% for message in messages %}
        <div class="text-center alert alert-{{ message.tags }}">
            {{ message|safe }}
        </div>
    {% endfor %}
{% endif %}
    
    {% block content %}
    <div class="row ">
        <div class="col-12    ">
            <form action=""  method="POST">
                {% csrf_token %}
                {{ form | crispy }}
                
                <br>
                <button type="submit" class="btn btn-success w-25 but-pos">ایجاد</button>
                <a href="{% url 'family:dashbord'%}" class="btn btn-success w-25  but-pos">برگشت</a>
            </form>
        </div>        
    </div>       
       <br>
    {% endblock content%}

loan/family/templates/family/loanlist.html
{% extends '../base3.html'%}
{% block title %}لیست وام {% endblock title %}

    
    {% block content %}
        

        <div class="row">
            <table class="table table-bordered table-hover table_pos">
                <thead>
                    <tr class="text-center text-white">
                        <th scope="col">#</th>
                        <th scope="col">وام</th>
                        <th scope="col">مبلغ وام</th>
                        <th scope="col">تعداد اقساط</th>
                        <th scope="col">مبلغ هر قسط</th>
                        <th scope="col">تاریخ شروع</th>
                        <th scope="col">وضعیت</th>
                        
                        {% if user.is_superuser or request.user.is_staf == true %}
                            <th scope="col">ویرایش</th>
                            <th scope="col">حذف</th>
                            <th scope="col">قرعه کشی</th>
                        {% endif %}
                        
                        
                    </tr>    
                </thead>
                <tbody>
                    {% for loan in loan_list %}
                        <tr class="text-center bg-white">
                            <th scope="row">{{loan.id}}</th>
                            <td>وام شماره {{loan.id}}</td>
                            <td>{{loan.m_vam}}</td>
                            <td>{{loan.t_gest}}</td>
                            <td>{{loan.m_ghest}}</td>
                            <td>{{loan.created}}</td>
                            <td class="p-2 text-nowrap">{{loan.choice}}</td>     
                            {% if user.is_superuser or request.user.is_staf == true %}
                            <td><a href="{% url 'family:vam_update' loan.id%}"><i class="fa-solid fa-pencil"></i></a></td>
                            <td><a href="{% url 'family:vam_delete' loan.id%}"><i class="fa-solid fa-trash-can"></i></a></td>
                            <td class="p-2 text-nowrap text-primary"><a href="{% url 'family:lottory' loan.id %}">قرعه کشی</a></td>
                            {% endif %}
                        </tr> 
                    {% endfor %}
                </tbody>
                           
            </table>
        </div>
      </div>



      
    {% endblock content %}

loan/family/templates/family/member_form.html
{% extends "../base3.html" %}

{%load crispy_forms_tags %}
{% block title %}اعضا{% endblock title %}


{% block content %}
 <div class="container mt-5">
        <div class="card">
            <h5 class="card-header">افزودن عضو</h5>
            <div class="card-body">
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ form | crispy }}

                    <div class="row mt-5">
                        <div class="d-flex col col-lg-4 col-sm-4 p-2 font-weight-light">
                            <button type="submit" class="btn btn-success col ml-1">ثبت اطلاعات</button>
                        </div>
                        <div class="d-flex col col-lg-4 col-sm-4 p-2 font-weight-light">
                            <a href="{% url 'family:dashbord' %}" class="btn btn-success col ml-1">پایان عضوگیری</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <br>
        <hr>


</div>
{% endblock content %}

loan/family/templates/family/memberlist.html
{% extends '../base3.html' %}
{% block title %}کاربران{% endblock title %}


{% block content %}
   
        <table class="table table-bordered table_pos">
            <thead class="text-center text-white ">
                <th scope="col">#</th>
                <th scope="col">شماره عضویت</th>
                <th scope="col">نام صندوق</th>
                <th scope="col">نام</th>
                <th scope="col">نام خانوادگی</th>
                <th scope="col">تعداد سهام</th>
                <th scope="col">شماره همراه</th>
                <th scope="col">تاریخ عضویت</th>
                <th scope="col">وضعیت</th>
                {% if user.is_superuser or request.user.is_staf == true %}
                <th scope="col">ویرایش</th>
                <th scope="col">حذف</th>
                {%endif%}
            </thead>
            {% for person in member_list %}
                <tbody class=" text-center bg-white">
                    <tr>
                        <td>#</td>
                        <td>{{person.id}}</td>
                        <td>{{person.membership}}</td>
                        <td>{{ person.name }}</td>
                        <td>{{person.family}}</td>
                        <td>{{person.t_saham}}</td>
                        <td>{{person.phone}}</td>
                        <td>{{person.created}}</td>
                        <td class="text-success">{{person.status}}</td>
                        {% if user.is_superuser or request.user.is_staf == true %}
                        <td><a href="{% url 'family:update' person.id %}"><i class="fa-solid fa-pencil"></i></a></td>
                        <td><a href="{% url 'family:delete' person.id %}"><i class="fa-solid fa-trash-can"></i></a></td>
                        {%endif%}
                    </tr>

                </tbody>
            {% endfor %}
        </table>

       
{% endblock content %}

loan/family/templates/family/sform.html
{%extends '../base.html'%}

{%load crispy_forms_tags %}
{%block title%}ساخت صندوق {%endblock title%}


{%block content%}
<div class="container mt-5">
    <p class="display-4 text-center">ساخت صندوق </p>
    <form action="" method="POST">
        {% csrf_token %}
            {{ form | crispy }}
         <div class="row">
            <div class="d-flex col ">
                <button type="submit" class="btn btn-success col ml-1 but-pos">مرحله بعد </button>
                <a href="{% url 'family:dashbord'%}" class="btn btn-success col but-pos">بازگشت</a>
            </div>

        </div>
        <br><br>

           
    </form>
</div>
    
{%endblock content%}

loan/family/templates/family/singup.html
{% extends '../base.html'%}

{%load crispy_forms_tags %}

{% block title%}ثبت نام{%endblock title%}
{%block content%}

<div class="container mt-5">
    <p class="display-4 text-center">ثبت نام</p>
    <form action="" method="POST">
        {% csrf_token %}

         {{form | crispy}}
         <br>
         <hr>
         <div class="row">
            <div class="d-flex col ">
                <button type="submit" class="btn btn-success col ml-1 but-pos">ثبت نام</button>
                <a href="{% url 'family:index'%}" class="btn btn-success col but-pos">بازگشت</a>
            </div>

        </div>
        <br><br>

           
    </form>
    {%endblock content%}

loan/family/templates/family/winnerlist.html
{% extends '../base3.html' %}
{% block title %}برندگان وام{% endblock title %}


{% block content %}
   
        <table class="table table-bordered table_pos">
            <thead class="text-center text-white ">
                <th scope="col">#</th>
                <th scope="col">شماره برنده</th>
                <th scope="col">اسم وام</th>
                <th scope="col">نام کاربر</th>
                <th scope="col">نام خانوادگی</th>
                <th scope="col">تاریخ</th>
              {% if user.is_superuser or user.is_staf %}
                <th scope="col">حذف</th>
              {%endif%}
            </thead>
            {% for win in winner_list %}
                <tbody class=" text-center bg-white text-nowrap">
                    <tr >
                        <td >#</td>
                        <td>{{win.id}}</td>
                        <td>{{win.loan}}</td>
                        <td>{{win.name}}</td>
                        <td>{{win.family}}</td>
                        <td>{{win.created}}</td>
                        {% if user.is_superuser or user.is_staf %}
                            <td><a href="{% url 'family:winner_delete' win.id %}"><i class="fa-solid fa-trash-can"></i></a></td>
                         {%endif%}
                     </tr>

                </tbody>
            {% endfor %}
        </table>

       
{% endblock content %}